#!/usr/bin/env python3
"""
Quick Deployment Script for QuantTime Servers

Interactive script to deploy R630XL and R810 servers with minimal manual intervention.
"""

import os
import sys
import json
import subprocess
import argparse
from pathlib import Path
from typing import Dict, Any

def print_banner():
    """Print deployment banner"""
    print("=" * 60)
    print("🚀 QuantTime Server Deployment")
    print("=" * 60)
    print("This script will help you deploy R630XL and R810 servers")
    print("for your quant homelab distributed computing infrastructure.")
    print("=" * 60)

def get_user_input(prompt: str, default: str = "") -> str:
    """Get user input with default value"""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        return input(f"{prompt}: ").strip()

def validate_ip(ip: str) -> bool:
    """Validate IP address format"""
    try:
        parts = ip.split('.')
        if len(parts) != 4:
            return False
        for part in parts:
            if not 0 <= int(part) <= 255:
                return False
        return True
    except:
        return False

def get_server_config() -> Dict[str, Any]:
    """Get server configuration from user"""
    config = {}
    
    print("\n📋 Server Configuration")
    print("-" * 30)
    
    # R630XL Configuration
    print("\n🖥️ R630XL Server Configuration:")
    config['r630xl'] = {
        'name': get_user_input("Server name", "r630xl"),
        'static_ip': get_user_input("Static IP address", "jupiter"),
        'gateway': get_user_input("Gateway IP", "192.168.2.1"),
        'tailscale_key': get_user_input("Tailscale auth key", ""),
        'username': get_user_input("SSH username", "quanttime"),
        'password': get_user_input("SSH password", "REDACTED_SSH_PASSWORD")
    }
    
    # R810 Configuration
    print("\n🖥️ R810 Server Configuration:")
    config['r810'] = {
        'name': get_user_input("Server name", "r810"),
        'static_ip': get_user_input("Static IP address", "saturn"),
        'gateway': get_user_input("Gateway IP", "192.168.2.1"),
        'tailscale_key': get_user_input("Tailscale auth key", ""),
        'username': get_user_input("SSH username", "quanttime"),
        'password': get_user_input("SSH password", "REDACTED_SSH_PASSWORD")
    }
    
    # GitHub Configuration
    print("\n🔗 GitHub Configuration:")
    config['github'] = {
        'repo_url': get_user_input("GitHub repository URL", "https://github.com/your-repo/QuantTime.git"),
        'token': get_user_input("GitHub token (optional)", "")
    }
    
    return config

def validate_config(config: Dict[str, Any]) -> bool:
    """Validate configuration"""
    print("\n🔍 Validating Configuration...")
    
    # Validate IP addresses
    for server_name, server_config in config.items():
        if server_name in ['r630xl', 'r810']:
            if not validate_ip(server_config['static_ip']):
                print(f"❌ Invalid IP address for {server_name}: {server_config['static_ip']}")
                return False
            
            if not validate_ip(server_config['gateway']):
                print(f"❌ Invalid gateway for {server_name}: {server_config['gateway']}")
                return False
            
            if not server_config['tailscale_key']:
                print(f"❌ Tailscale auth key required for {server_name}")
                return False
    
    print("✅ Configuration validation passed")
    return True

def generate_setup_scripts(config: Dict[str, Any]):
    """Generate setup scripts for each server"""
    print("\n📝 Generating Setup Scripts...")
    
    script_dir = Path("server/setup")
    script_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate R630XL setup script
    r630xl_script = script_dir / "setup_r630xl.sh"
    with open(r630xl_script, 'w') as f:
        f.write(f"""#!/bin/bash
# R630XL Setup Script
# Generated by quick_deploy.py

echo "🚀 Setting up R630XL server..."

# Run the main setup script
sudo ./ubuntu_server_setup.sh \\
  --server-name {config['r630xl']['name']} \\
  --static-ip {config['r630xl']['static_ip']} \\
  --gateway {config['r630xl']['gateway']} \\
  --tailscale-key {config['r630xl']['tailscale_key']} \\
  --github-token {config['github']['token']}

echo "✅ R630XL setup complete!"
""")
    
    # Generate R810 setup script
    r810_script = script_dir / "setup_r810.sh"
    with open(r810_script, 'w') as f:
        f.write(f"""#!/bin/bash
# R810 Setup Script
# Generated by quick_deploy.py

echo "🚀 Setting up R810 server..."

# Run the main setup script
sudo ./ubuntu_server_setup.sh \\
  --server-name {config['r810']['name']} \\
  --static-ip {config['r810']['static_ip']} \\
  --gateway {config['r810']['gateway']} \\
  --tailscale-key {config['r810']['tailscale_key']} \\
  --github-token {config['github']['token']}

echo "✅ R810 setup complete!"
""")
    
    # Make scripts executable
    os.chmod(r630xl_script, 0o755)
    os.chmod(r810_script, 0o755)
    
    print(f"✅ Generated setup scripts:")
    print(f"   - {r630xl_script}")
    print(f"   - {r810_script}")

def generate_deployment_guide(config: Dict[str, Any]):
    """Generate deployment guide with actual configuration"""
    print("\n📖 Generating Deployment Guide...")
    
    guide_path = Path("server/docs/DEPLOYMENT_GUIDE_QUICK.md")
    guide_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(guide_path, 'w') as f:
        f.write(f"""# Quick Deployment Guide

## Generated Configuration

### R630XL Server
- **Name**: {config['r630xl']['name']}
- **Static IP**: {config['r630xl']['static_ip']}
- **Gateway**: {config['r630xl']['gateway']}
- **Username**: {config['r630xl']['username']}

### R810 Server
- **Name**: {config['r810']['name']}
- **Static IP**: {config['r810']['static_ip']}
- **Gateway**: {config['r810']['gateway']}
- **Username**: {config['r810']['username']}

## Quick Deployment Steps

### Step 1: Prepare Servers
1. Install Ubuntu 22.04 on both servers
2. Create user: `{config['r630xl']['username']}`
3. Set password: `{config['r630xl']['password']}`

### Step 2: Download Setup Scripts
```bash
# On R630XL
wget https://raw.githubusercontent.com/your-repo/QuantTime/main/server/setup/ubuntu_server_setup.sh
chmod +x ubuntu_server_setup.sh

# On R810
wget https://raw.githubusercontent.com/your-repo/QuantTime/main/server/setup/ubuntu_server_setup.sh
chmod +x ubuntu_server_setup.sh
```

### Step 3: Run Setup Scripts
```bash
# On R630XL
sudo ./ubuntu_server_setup.sh \\
  --server-name {config['r630xl']['name']} \\
  --static-ip {config['r630xl']['static_ip']} \\
  --gateway {config['r630xl']['gateway']} \\
  --tailscale-key {config['r630xl']['tailscale_key']} \\
  --github-token {config['github']['token']}

# On R810
sudo ./ubuntu_server_setup.sh \\
  --server-name {config['r810']['name']} \\
  --static-ip {config['r810']['static_ip']} \\
  --gateway {config['r810']['gateway']} \\
  --tailscale-key {config['r810']['tailscale_key']} \\
  --github-token {config['github']['token']}
```

### Step 4: Verify Installation
```bash
# Check services
sudo systemctl status quanttime-api-server
sudo systemctl status quanttime-data-collector
sudo systemctl status quanttime-celery-worker
sudo systemctl status quanttime-monitoring

# Check network
tailscale ip -4
ip addr show

# Check health
quanttime-health
```

### Step 5: Update Dashboard Configuration
Update `server/config/servers.json` with the actual Tailscale IPs obtained from the servers.

### Step 6: Launch Dashboard
```bash
python run.py dashboard --port 8501
```

## Next Steps
1. Test server connections in the dashboard
2. Submit test tasks to verify functionality
3. Configure data sources and API keys
4. Set up monitoring and alerts

---
Generated by quick_deploy.py
""")
    
    print(f"✅ Generated deployment guide: {guide_path}")

def main():
    """Main deployment function"""
    parser = argparse.ArgumentParser(description="Quick deployment for QuantTime servers")
    parser.add_argument("--config", help="Path to configuration file")
    parser.add_argument("--generate-only", action="store_true", help="Generate scripts only, don't deploy")
    
    args = parser.parse_args()
    
    print_banner()
    
    # Load or get configuration
    if args.config and Path(args.config).exists():
        with open(args.config, 'r') as f:
            config = json.load(f)
        print(f"📋 Loaded configuration from {args.config}")
    else:
        config = get_server_config()
        
        # Save configuration
        config_path = Path("server/config/deployment_config.json")
        config_path.parent.mkdir(parents=True, exist_ok=True)
        with open(config_path, 'w') as f:
            json.dump(config, f, indent=2)
        print(f"💾 Saved configuration to {config_path}")
    
    # Validate configuration
    if not validate_config(config):
        print("❌ Configuration validation failed")
        sys.exit(1)
    
    # Generate setup scripts
    generate_setup_scripts(config)
    
    # Generate deployment guide
    generate_deployment_guide(config)
    
    if args.generate_only:
        print("\n✅ Script generation complete!")
        print("Run the generated setup scripts on your servers to complete deployment.")
        return
    
    # Ask for deployment confirmation
    print("\n🚀 Ready to deploy servers!")
    print("This will:")
    print("1. Generate setup scripts")
    print("2. Create deployment guide")
    print("3. Provide instructions for manual deployment")
    
    confirm = input("\nContinue with deployment? (y/N): ").strip().lower()
    if confirm != 'y':
        print("Deployment cancelled.")
        return
    
    print("\n✅ Deployment preparation complete!")
    print("\n📋 Next Steps:")
    print("1. Copy the generated setup scripts to your servers")
    print("2. Run the setup scripts on each server")
    print("3. Update the dashboard configuration with actual Tailscale IPs")
    print("4. Launch the dashboard and test connections")
    print("\n📖 See server/docs/DEPLOYMENT_GUIDE_QUICK.md for detailed instructions")

if __name__ == "__main__":
    main()
